In [3]:
import torch

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5

In [4]:
float_tensor =torch.randn(3,4,5).float()
float_tensor

tensor([[[ 7.1969e-01, -5.6734e-01,  6.0060e-02,  1.7912e+00,  1.7122e+00],
         [ 1.8449e-01, -8.8299e-01, -1.6526e+00, -2.3604e+00, -1.3796e+00],
         [ 7.7389e-01, -1.1597e+00, -1.8535e+00,  2.1576e-01,  1.0610e+00],
         [ 3.3332e-02,  2.0142e+00, -9.5532e-01, -1.3384e+00,  2.6114e-01]],

        [[-2.7094e+00, -9.4065e-01,  6.6098e-01,  2.0731e+00,  1.1771e+00],
         [-3.5521e-01, -3.3260e-01,  2.9529e-01,  6.3992e-02,  1.2864e+00],
         [-3.4173e-02,  2.1522e-03,  1.4472e+00,  3.3250e-02,  1.4745e+00],
         [-6.6555e-01, -1.1727e+00,  2.1216e+00,  8.5909e-01, -4.9705e-01]],

        [[-8.7448e-01, -4.9128e-02, -4.7678e-02, -8.9461e-01,  6.3056e-01],
         [-6.6279e-01, -7.4088e-01,  1.0552e+00, -4.2764e-01, -4.9488e-01],
         [-1.0983e+00, -1.6140e+00,  8.3601e-01, -4.4530e-01, -1.2242e-01],
         [-2.1556e-01, -4.0915e-01,  1.3771e-01,  8.0971e-01, -1.6369e+00]]])

In [5]:
# Выведите его форму (shape)
float_tensor.shape

torch.Size([3, 4, 5])

In [6]:
# Приведите его к форме 6 X 10
float_tensor = float_tensor.reshape(6, 10)
float_tensor.size()

torch.Size([6, 10])

In [11]:
#  Создайте случайный IntTensor размера 10
int_tensor = torch.randn(10).int()
int_tensor

tensor([0, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=torch.int32)

In [12]:
float_tensor * int_tensor # оба операнда имеют разные размеры, поэтому их невозможно поэлементно никак перемножить

tensor([[ 0.0000, -0.0000,  0.0000,  0.0000,  0.0000,  0.1845, -0.8830, -0.0000,
         -0.0000, -0.0000],
        [ 0.0000, -0.0000, -0.0000,  0.0000,  0.0000,  0.0333,  2.0142, -0.0000,
         -0.0000,  0.0000],
        [-0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.3552, -0.3326,  0.0000,
          0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000,  0.0000,  0.0000, -0.6656, -1.1727,  0.0000,
          0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.6628, -0.7409,  0.0000,
         -0.0000, -0.0000],
        [-0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.2156, -0.4091,  0.0000,
          0.0000, -0.0000]])

In [13]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

A = float_tensor.mm(float_tensor.T)
A.size()

torch.Size([6, 6])

In [19]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

y.backward()
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [20]:
# Создайте единичный тензор размера 5x6

a_tensor = torch.randn(5, 6)

In [29]:
print('w:', linear.weight)
print('b:', linear.bias)

w: Parameter containing:
tensor([[ 0.1969,  0.4566],
        [-0.3301,  0.1606]], requires_grad=True)
b: Parameter containing:
tensor([-0.3316, -0.6003], requires_grad=True)


In [21]:
# Переведите его в формат numpy
a_tensor.numpy()

array([[ 0.26505798, -0.52714837,  0.51125807,  0.538932  , -0.18151481,
        -0.28546146],
       [-0.6936106 ,  0.9071116 , -1.4272387 ,  2.0002835 ,  1.7845782 ,
        -0.2633531 ],
       [ 0.27946874,  1.021883  ,  0.12097345,  0.9489974 ,  0.2229469 ,
        -0.499397  ],
       [-0.18166383, -0.04163698,  1.0309905 ,  0.5523192 , -0.6217929 ,
        -1.0757676 ],
       [-1.0505118 ,  0.02721093,  0.9409388 , -0.30473244, -0.36780533,
         0.60064083]], dtype=float32)